services:
  notification-service:
    image: ghcr.io/zoroplay/notification-service:latest
    container_name: notification-service
    ports:
      - "9013:5000"
      - "9020:3020"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - sbenet
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 256M

networks:
  sbenet:
    external: true